### ISSUE TITLE
Support for shelter/workmode

### ISSUE THREAD

**Issue by nr458h** [light-launcher/Light-Android-Launcher#50]
Hi do you think it is possible to add support for apps within shelter or work because at the moment they don't show up in the "All App list"

Thanks

**Comment by jancborchardt** [comment]
Sorry for the late reply here. I assume you mean this [Shelter](https://play.google.com/store/apps/details?id=net.typeblog.shelter) app and the Android "Work" profile?

Since I have no experience with using these, could you describe what would be a possible solution that would fix this for you? (E.g. do you switch a mode, and then other apps should show in the All apps list? Or should sheltered apps simply show in the list? Or after a subheading / whitespace?)

**Comment by Shadowspear123** [comment]
For me, workspace shows up in the all apps list, clicking on it shows apps installed with Shelter.

**Comment by jancborchardt** [comment]
So we can close this? Or @nr458h does this still happen? If so, could you provide some details, screenshots and background info like versions etc.?

**Comment by nr458h** [comment]
Sorry for not responding at all - thanks for implementation
