### ISSUE TITLE
Edit Name for Apps

### ISSUE THREAD

**Issue by nr458h** [light-launcher/Light-Android-Launcher#52]
For example when I use the Tor Browser in the list it is named as
Tor Browser for Android (alpha)
In my opinion therefore it would be great if I could edit the names of the apps

**Comment by jancborchardt** [comment]
There’s a similar thing where Fennec is called "Fennec F-Droid" which is a bit annoying.

Not sure if editable names are a good way to go as then _everyone_ needs to do it manually. I’d say we can simply have a reasonable list, and a start can be:
- Tor Browser for Android (alpha) → Tor Browser
- Fennec F-Droid → Fennec
- …

**Comment by github-tomster** [comment]
@those-who-assemble-the-code
first: the publisher of the app has prescribed how his application is displayed on the launcher
second: the publisher of the launcher has prescribed how the application is displayed
result: nothing for the user, just seems disruptive...

so indeed something so basic like editing a 'shortcut name' could result in a
better user experience...

**Comment by jancborchardt** [comment]
> so indeed something so basic like editing a 'shortcut name' could result in a
better user experience...

That would require people manually doing editing work. This might sound nice, but from experience a) it’s not nice work, and if you reinstall you have to do it again and b) people are not even going to find or use it. :\

**Comment by github-tomster** [comment]
here we go again!

**Comment by jancborchardt** [comment]
@github-tomster the tone of these is seriously demotivating and takes any fun out of discussion or working on a project. I already saw it in another project I work on (Nextcloud) and see it here just the same. Please consider that there’s other humans reading your comments and working on the apps that you request things for. Thank you.

-------------

> maybe someone wants the freedom of choice to edit the name of an app in the launcher/app-drawer?
great, i like that and i want it too!
> to be honest: for ages i am using an tool(root-required) to edit/hack names of apps in the app-drawer/launcher

So you already know how to do that, just keep on doing that. Other people don’t want to spend their time on that, and we want to develop software which makes things easy, not more difficult. :+1: 

----


Designs are made based on what the underlying problem is. The underlying problem here for example is "Some apps have long convoluted names". Making the names editable is not a proper fix because then everyone needs to manually edit this. Adjusting it to a reasonable default would be an option for a fix. Not saying it’s the best solution, but it’s definitely more smooth than requiring everyone to edit the names.

**Comment by github-tomster** [comment]
@jancborchardt 
seems our views are the same, my perspective is the user-one and yours the 'contributor'-one
i am also sad and demotivated to see such an approach to a solution. 
maybe the topic has the very wrong title.
would it read: truncate app-names, i wouldnt be here at all.
but silly me saw the chance: editable names on the launcher/drawer. finally! (and rootless)

> Designs are made based on what the underlying problem is.
 
indeed, the vast majority is not able to edit a name.
a proprietary-list nicely masks the problem.
it is a good fix.

pardon for misunderstanding the ' Edit Name for Apps #52 ' title

@who-cares
problem:

- app-names to long/convoluted
- user can not edit name for apps

possible solution:

- add an option to use internal-proprietary-launcher-list (maintained-by-jancborchardt ;-) )
[hope that the maintainer has always all 'truncate-worthy' names included]
- use internal-proprietary-launcher-list per default to help the no-skilled vast majority
- dont forget to give an option to deactivate internal-proprietary-launcher-list
- make names of apps editable

off-topic
@jancborchardt 
you cant even imagine how much fun your nextcloud font-stunt annihilated on earth!

**Comment by jancborchardt** [comment]
You forgot another possible solution:

- We leave it as it is since either approach is too much work. ;)

----

> my perspective is the user-one and yours the 'contributor'-one

That’s an assumption. My assumption is that your perspective is one of a power-user (since you know how to root your phone and know what Github is) and mine is the one of a UX-focused designer who does usability testing with non-power-users. So we both want solutions, it’s just a question of at which level.

-------

Also off-topic @github-tomster There have been so many other things apart from that font change issue. The more stuff is done, the more can also go wrong from time to time. It happens to everyone and everywhere. It’s not a reason to be aggressive or demanding, but to support others.

**Comment by nr458h** [comment]
I will close this request because I don't want provide a plattform for (in my opinion) making fun of people how spend their free time working on an app and give it for free to all interested people.

Related to the 'discussion' I'm with Jan, because making a great user experience I offer what the user needs and not what he wants.

**Comment by github-tomster** [comment]
> You forgot another possible solution:
> 
>     * We leave it as it is since either approach is too much work. ;)
as i already wrote, i am fine with that.
same as it ever was.

> > my perspective is the user-one and yours the 'contributor'-one
> 
> That’s an assumption. 
My assumption is that your perspective is one of a power-user (since you know how to root your phone and know what Github is) and mine is the one of a UX-focused designer who does usability testing with non-power-users. So we both want solutions, it’s just a question of at which level.

got it!
that explains a lot!
 
> Also off-topic @github-tomster There have been so many other things apart from that font change issue. The more stuff is done, the more can also go wrong from time to time. It happens to everyone and everywhere. It’s not a reason to be aggressive or demanding, but to support others.

well, my posts are my support. and not all like them all the time.
reading the issue again makes me lol
me totally lost and upset and the contributors not even knowing which is the right font!
and at last only two other beings participated. so sad.


> I will close this request because I don't want provide a plattform for (in my opinion) making fun of people how spend their free time working on an app and give it for free to all interested people.
> 
wow.

> Related to the 'discussion' I'm with Jan, because making a great user experience I offer what the user needs and not what he wants.

what an excellent summary!
