### ISSUE TITLE
Delay when opening all app screen

### ISSUE THREAD

**Issue by Shadowspear123** [light-launcher/Light-Android-Launcher#63]
Hi, I really like this app.
There is one problem though, when I swipe up for the all apps list, there is a delay and a stutter before the list opens.

Also, I was wondering if there was a way the + could be hidden on the home screen?

**Comment by jancborchardt** [comment]
Yes, this is because it’s not a direct swipe of an element but rather the gesture of swiping up triggers the animation of the "All apps" list.

I agree that it feels indirect and is a delay. As talked about before @postapczuk – any idea there? Ideally it would be a panel you swipe up from the bottom, kind of like the notifications tray on the top (which you can also swipe back up in the middle and it feels responsive).


----

@Shadowspear123 for the `+` question, please open a separate issue. :)

**Comment by postapczuk** [comment]
@jancborchardt it's not by the trigger, it's issue with loading app list directly, then performing animation. It should be done simultaneously while performing animation.

**Comment by postapczuk** [comment]
There are solutions to that:
1. Loading apps while starting lalauncher (but then needs solution for refreshing it on uninstall)
2. Loading simultaneously in separate thread, while performing animation

**Comment by postapczuk** [comment]
done
