### ISSUE TITLE
Duplicate name bug

### ISSUE THREAD

**Issue by oscarbenedito** [light-launcher/Light-Android-Launcher#78]
If two apps have the same name (for instance the default camera and the Simple Camera app both appear as "Camera") only one of them is able to be launched (whether you launch the first or the second entry, the same app is always launched).

**Comment by acorreya** [comment]
I am facing the same bug, but just that the cameras are stock cam and gcam, which show as __Camera__. Both Camera entries open the stock cam, probably because it has alphabetical precedence.

**Comment by taylor-josh** [comment]
Thanks for reporting this issue :)

The issue here is in the way that the apps are launched
Please refer to the same log

![image](https://user-images.githubusercontent.com/39976320/79289765-39ea3300-7e98-11ea-8d89-edd940a15708.png)

In the screenshot above, in green, this is the "app name" (or what is referred to as the _label_ of the app); in yellow is the package name. Note that the "app name" for Simple Camera and the pre-installed Google Camera are the same.

The array holding the names of the apps is storing the package names, which is fine, but in the OnClickHandler, is using the "app name" to determine which app to run. So in this case, with two apps with an "app name" of Camera, both launch the same app, as you said.

Let me see if I can take some time to take a stab at this issue and resolve.

**Comment by postapczuk** [comment]
@taylor-josh 
I'll do the release to fdroid right after this fix.

Thank you for your effort.

**Comment by taylor-josh** [comment]
I was able to fix the issue described. The only problem here that is left is that the names of the apps will still be the same in the lists. This is because, at least in the example @oscarbenedito and @acorreya mentioned, both apps have the same app name/label name although they are different apps.

Easiest solution going forward might be to look at allowing the ability to rename the labels that we display in the list. Or see if there is something else we can use for the app names in the lists to differentiate them in a unique way. that aspect would need further research.
